- src/main/java/org/apache/maven/plugins/jlink/JLinkMojo.java
> Added option for generating jlink launcher.

- src/it/projects/MJLINK-3_improveVerboseOutput/pom.xml
- src/it/projects/cli-options/bind-services/pom.xml
- src/it/projects/cli-options/compress-0/pom.xml
- src/it/projects/cli-options/compress-1/pom.xml
- src/it/projects/cli-options/compress-2/pom.xml
- src/it/projects/cli-options/disable-plugin/pom.xml
- src/it/projects/cli-options/endian-big/pom.xml
- src/it/projects/cli-options/endian/pom.xml
- src/it/projects/cli-options/ignore-signing-information/pom.xml
- src/it/projects/cli-options/no-header-files/pom.xml
- src/it/projects/cli-options/no-man-pages/pom.xml
- src/it/projects/cli-options/strip-debug/pom.xml
- src/it/projects/cli-options/suggest-providers/pom.xml
- src/it/projects/setup-jar-module-info/pom.xml
- src/it/projects/setup-jar/pom.xml
Hi!
In this Pull Request, I've just upgraded the version of maven-compiler-plugin to version 3.8.0 in ITs and I tested it on:
- Maven 3.5.4, Java 9.0.4-open
- Maven 3.5.4, Java 10.0.2-oracle
- Maven 3.5.4, Java 11.0.1-open
- Maven 3.6.0, Java 9.0.4-open
- Maven 3.6.0, Java 10.0.2-oracle
- Maven 3.6.0, Java 11.0.1-open
Thanks,
André Tadeu de Carvalho
is to use the JIRA issue title in the pull request title and in the first line of …
> [MJLINK-29] Upgrade maven-compiler-plugin to version 3.8.0 in ITs.

- pom.xml
- Set Java 8 as minimum
- Update plugins and dependencies
To make …
> [MJLINK-50] upgrade to Java 8 / Maven 3.1.0

- pom.xml
- src/it/projects/MJLINK-9_reactor/api/pom.xml
- src/it/projects/MJLINK-9_reactor/api/src/main/java/com/reactor/project/api/Currency.java
- src/it/projects/MJLINK-9_reactor/api/src/main/java/com/reactor/project/api/Money.java
- src/it/projects/MJLINK-9_reactor/api/src/main/java/module-info.java
- src/it/projects/MJLINK-9_reactor/app/pom.xml
- src/it/projects/MJLINK-9_reactor/app/src/main/java/com/reactor/project/app/App.java
- src/it/projects/MJLINK-9_reactor/app/src/main/java/module-info.java
- src/it/projects/MJLINK-9_reactor/invoker.properties
- src/it/projects/MJLINK-9_reactor/pom.xml
- src/it/projects/MJLINK-9_reactor/verify.groovy
- pomIncludes refined for reactor modules (as already present)
To …
> [MJLINK-9] add test for multi-module reactor project

- src/it/projects/MJLINK-40_includeLocales/invoker.properties
- src/it/projects/MJLINK-40_includeLocales/pom.xml
- src/it/projects/MJLINK-40_includeLocales/verify.groovy
- src/main/java/org/apache/maven/plugins/jlink/JLinkMojo.java
> [MJLINK-40] add --include-locales option.

- src/test/java/org/apache/maven/plugins/jlink/AbstractJLinkMojoTest.java
> [MJLINK-56] Use Junit5 imports, add display name, remove commented code.

- src/site/apt/index.apt.vm
- src/site/apt/usage.apt.vm
- remove alpha release text.
- Do not tell the user they need a multi-module project.
- remove superfluous '}'.
----
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if …
> [MJLINK-49] documentation update

- src/main/java9/org/apache/maven/plugins/jlink/JLinkExecutor.java
> [MJLINK-62] Use StringWriter for BAOS.

- pom.xml
- move plexus-utils-version to dependencyManagement
--- 
To make …
> [MJLINK-63] update plexus-java

- .github/workflows/maven.yml
- INFRA created an allowlist, battila7/jdk-via-jabba is not on that list.
- See https://github.com/apache/maven-jlink-plugin/actions/runs/492727057
---
[Individual Contributor License …
> (build) update GH actions to supported toolchain JDK

- .github/workflows/maven.yml
Adds back OpenJ9 to the build matrix. JLink can differ from dist to dist, and OpenJ9 is the only very distinctive distribution next to any other hotspot JVM.
Please also vote for IBM Semeru inclusion by clicking 'thumbs up' on the first comment: https://github.com/actions/setup-java/pull/289#issue-1123567834 
---
be performed on …
> [BUILD] add OpenJ9 to build matrix

- pom.xml
> [MJLINK-70] update site-plugin to v3.12.1

- pom.xml
- src/main/java/org/apache/maven/plugins/jlink/AbstractJLinkExecutor.java
- src/main/java/org/apache/maven/plugins/jlink/AbstractJLinkMojo.java
- src/main/java/org/apache/maven/plugins/jlink/AbstractJLinkToolchainExecutor.java
- src/main/java/org/apache/maven/plugins/jlink/JLinkExecutor.java
- src/main/java/org/apache/maven/plugins/jlink/JLinkMojo.java
- src/test/java/org/apache/maven/plugins/jlink/AbstractJLinkMojoTest.java
> [MJLINK-71] require maven 3.6.3

- src/main/java/org/apache/maven/plugins/jlink/AbstractJLinkToolchainExecutor.java
- src/main/java/org/apache/maven/plugins/jlink/JLinkMojo.java
- src/test/java/org/apache/maven/plugins/jlink/JLinkMojoTest.java
> [MJLINK-64] add quoting on forking

- pom.xml
- src/main/java/org/apache/maven/plugins/jlink/JLinkExecutor.java
> [MJLINK-72] remove commons-lang3

- pom.xml
> [MJLINK-76] - Upgrade maven-plugin parent to 41

- pom.xml
- src/it/projects/MJLINK-80_additionalResources/pom.xml
- src/it/projects/MJLINK-80_additionalResources/src/jlink/resources/README.md
- src/it/projects/MJLINK-80_additionalResources/verify.groovy
- src/main/java/org/apache/maven/plugins/jlink/JLinkMojo.java
> [MJLINK-80] Support additional resources

- src/main/java/org/apache/maven/plugins/jlink/AbstractJLinkMojo.java
- src/main/java/org/apache/maven/plugins/jlink/AbstractJLinkToolchainExecutor.java
Mostly I want to see if the build is broken on Windows with an innocuous change
> API doc copy edits

- src/site/apt/index.apt.vm
and various grammar and style fixes
> There are no examples

- src/it/projects/cli-options/add-options/verify.groovy
- src/main/java/org/apache/maven/plugins/jlink/JLinkMojo.java
JDK 25 accepts `--add-options` jlink option with `=` only due to JDK-8303884.
See [GitHub PR on OpenJDK](https://github.com/openjdk/jdk/pull/22526) for more details.
Currently Maven JLink Plugin generates jlink arguments separated by white space. It works fine on JDK 24 or earlier, but it will not work on JDK 25 or later. jlink (in JDK 24 or earlier) can be accept both style `--add-options <opts>` and `--add-options=<opts>`. Thus we can adopt `--add-options=` style for all JDK versions.
---
where you …
> [MJLINK-91] addOptions should concatenate arguments with "="

- src/test/java/org/apache/maven/plugins/jlink/JLinkMojoTest.java
for the change (usually before you start working on it).  Trivial changes like typos do not
require a GitHub issue.  Your pull request should address just this issue, without
where you replace `#<num>` with the appropriate GitHub issue. Best practice
is to use the GitHub issue title in the pull request title and in the first line of the
the [Apache …
> Fix the checkstyle violation introduced in the new version of the parent pom
